/**
 * Build-time data injection script.
 *
 * Reads results/leaderboard.json and generates src/data/data.js
 * with LOCALES and PROVIDERS arrays populated.
 *
 * Usage: node leaderboard/scripts/inject-data.js
 */

import { readFileSync, writeFileSync } from "fs";
import { execSync } from "child_process";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const leaderboardJsonPath = join(__dirname, "..", "..", "results", "leaderboard.json");
const significanceJsonPath = join(__dirname, "..", "..", "results", "significance.json");
const manifestPath = join(__dirname, "..", "..", "manifest.json");
const submissionsBase = join(__dirname, "..", "..", "submissions", "normalized");
const dataPath = join(__dirname, "..", "src", "data", "data.js");

let locales = [];
let providers = [];

try {
    const raw = readFileSync(leaderboardJsonPath, "utf-8");
    const data = JSON.parse(raw);
    if (Array.isArray(data.locales)) locales = data.locales;
    if (Array.isArray(data.providers)) providers = data.providers;
    console.log(`Injecting ${locales.length} locales and ${providers.length} providers from leaderboard.json`);
} catch (e) {
    console.warn(`Warning: could not read leaderboard.json (${e.message}), using empty data`);
}

// Significance + variance from results/significance.json. Empty defaults so
// the widget can still render in dev when scoring hasn't been run yet.
let significanceMetrics = {};
let varianceBlock = {};
let significanceProviders = [];
try {
    const raw = readFileSync(significanceJsonPath, "utf-8");
    const data = JSON.parse(raw);
    if (data.metrics && typeof data.metrics === "object") significanceMetrics = data.metrics;
    if (data.variance && typeof data.variance === "object") varianceBlock = data.variance;
    if (Array.isArray(data.providers)) significanceProviders = data.providers;
    const metricKeys = Object.keys(significanceMetrics);
    console.log(
        `Injecting significance: ${metricKeys.length} metrics (${metricKeys.join(", ")}) ` +
            `+ variance for ${Object.keys(varianceBlock).length} providers`,
    );
} catch (e) {
    console.warn(`Warning: could not read significance.json (${e.message}), using empty data`);
}

const AUDIO_SAMPLES = {
    "en-US": "conv-39-turn-8",
    "es-MX": "conv-49-turn-5",
    "tr-TR": "conv-41-turn-11",
    "vi-VN": "conv-20-turn-14",
    "zh-CN": "conv-4-turn-12",
};

const CURATED_SAMPLES = {
    "en-US": ["conv-39-turn-8", "conv-48-turn-3", "conv-14-turn-11", "conv-0-turn-9", "conv-17-turn-4"],
    "es-MX": ["conv-49-turn-5", "conv-2-turn-1", "conv-47-turn-1", "conv-29-turn-11", "conv-14-turn-15"],
    "tr-TR": ["conv-41-turn-11", "conv-22-turn-2", "conv-40-turn-11", "conv-14-turn-10", "conv-2-turn-0"],
    "vi-VN": ["conv-20-turn-14", "conv-26-turn-3", "conv-42-turn-2", "conv-7-turn-13", "conv-3-turn-7"],
    "zh-CN": ["conv-4-turn-12", "conv-0-turn-6", "conv-7-turn-6", "conv-1-turn-10", "conv-39-turn-17"],
};

let sampleUtterances = {};
try {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
    const byLocale = {};
    for (const u of manifest.utterances) {
        (byLocale[u.locale] ||= []).push(u);
    }
    const providerIds = providers.map((p) => p.id);

    for (const loc of Object.keys(byLocale).sort()) {
        const audioId = AUDIO_SAMPLES[loc];
        const curatedIds = CURATED_SAMPLES[loc] || [];
        const picks = curatedIds.map((id) => byLocale[loc].find((u) => u.id === id)).filter(Boolean);

        sampleUtterances[loc] = picks.map((u) => {
            const subs = {};
            for (const pid of providerIds) {
                try {
                    subs[pid] = readFileSync(join(submissionsBase, pid, loc, u.id + ".txt"), "utf-8").trim();
                } catch {
                    /* file may not exist */
                }
            }
            return {
                id: u.id,
                locale: loc,
                transcript: u.transcript,
                hasAudio: u.id === audioId,
                submissions: subs,
            };
        });
    }
    const total = Object.values(sampleUtterances).reduce((s, a) => s + a.length, 0);
    console.log(`Injecting ${total} sample utterances across ${Object.keys(sampleUtterances).length} locales`);
} catch (e) {
    console.warn(`Warning: could not build sample utterances (${e.message})`);
}

const output = `// Auto-generated by scripts/inject-data.js — do not edit manually

export const LOCALES = ${JSON.stringify(locales, null, 4)};

export const PROVIDERS = ${JSON.stringify(providers, null, 4)};

export const SAMPLE_UTTERANCES = ${JSON.stringify(sampleUtterances, null, 4)};

// Pairwise significance + per-metric means from
// scripts/significance_test.py (conversation-level paired bootstrap).
// Provider order matches significance.json#/providers (best -> worst,
// per the metric chosen at output-json write time).
export const SIGNIFICANCE_PROVIDERS = ${JSON.stringify(significanceProviders, null, 4)};

export const SIGNIFICANCE = ${JSON.stringify(significanceMetrics, null, 4)};

// Variance block: tmp/aggregate_variance.py output. Per-provider per-locale
// {wer:{mean,std}, significantWer:{mean,std}, _n_waves, _wave_n_utterances}.
export const VARIANCE = ${JSON.stringify(varianceBlock, null, 4)};

/**
 * Get the score for a provider given filters.
 * If locale is 'overall', averages across all locales.
 */
export function getProviderScore(provider, metricKey, locale) {
    if (locale === "overall") {
        const scores = LOCALES.map(l => {
            const result = provider.localeResults[l.code];
            return result && result[metricKey] !== undefined && result[metricKey] !== null
                ? result[metricKey]
                : null;
        });
        if (scores.some(s => s === null)) return null;
        const avg = scores.reduce((a, b) => a + b, 0) / scores.length;
        return Math.round(avg * 100) / 100;
    }

    const result = provider.localeResults[locale];
    if (result && result[metricKey] !== undefined && result[metricKey] !== null) {
        return result[metricKey];
    }
    return null;
}

/**
 * Get per-locale scores for a provider (used in expanded rows).
 */
export function getProviderLocaleScores(provider, metricKey) {
    return LOCALES.map(locale => {
        const score = getProviderScore(provider, metricKey, locale.code);
        return {
            ...locale,
            score,
        };
    });
}
`;

writeFileSync(dataPath, output, "utf-8");

try {
    execSync(`npx prettier --write "${dataPath}"`, {
        cwd: join(__dirname, ".."),
        stdio: "inherit",
    });
} catch (e) {
    console.warn(`Warning: prettier --write failed (${e.message}); generated file may fail lint check`);
}

console.log(`Wrote ${dataPath}`);
