name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e11487 # v4

      - name: Install ruff
        run: pip install ruff

      - name: Check formatting
        run: ruff format --check scripts/ scoring/

      - name: Check lint rules
        run: ruff check scripts/ scoring/

  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e11487 # v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5 # v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci
        working-directory: leaderboard

      - name: ESLint
        run: npx eslint src/ scripts/
        working-directory: leaderboard

      - name: Prettier
        run: npx prettier --check src/ scripts/
        working-directory: leaderboard
